networks:
  expense-tracker-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-tracker-app-prod
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      expense-tracker-network:
        ipv4_address: 172.28.0.3
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://expense_user:expense_secure_password_2024@172.28.0.2:5432/expense_tracker
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "node -e \"require('http').get('http://localhost:3000/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1))\""]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  postgres:
    image: postgres:16-alpine
    container_name: expense-tracker-db-prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: expense_tracker
      POSTGRES_USER: expense_user
      POSTGRES_PASSWORD: expense_secure_password_2024
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      expense-tracker-network:
        ipv4_address: 172.28.0.2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U expense_user -d expense_tracker"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  postgres_data_prod:
    driver: local