networks:
  expense-tracker-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24

services:
  postgres:
    image: postgres:16-alpine
    container_name: expense-tracker-db-simple
    restart: unless-stopped
    environment:
      POSTGRES_DB: expense_tracker
      POSTGRES_USER: expense_user
      POSTGRES_PASSWORD: expense_secure_password_2024
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data_simple:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5434:5432"
    networks:
      expense-tracker-network:
        ipv4_address: 172.28.0.2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U expense_user -d expense_tracker"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  postgres_data_simple:
    driver: local