version: '3.8'

services:
  app:
    image: node:22
    container_name: expense-tracker-dev
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./prisma/dev.db
    command: >
      sh -c "
        npm install &&
        npm run dev -- --host 0.0.0.0 --port 5173
      "
    networks:
      - expense-tracker-dev

networks:
  expense-tracker-dev:
    driver: bridge