import { d as derived, w as writable } from "./index.js";
const common$1 = { "confirm": "Confirm", "cancel": "Cancel", "delete": "Delete", "edit": "Edit", "save": "Save", "close": "Close", "loading": "Loading...", "search": "Search", "filter": "Filter", "reset": "Reset", "apply": "Apply", "yes": "Yes", "no": "No", "back": "Back", "done": "Done" };
const navigation$1 = { "transactions": "Transactions", "dashboard": "Dashboard", "categories": "Categories", "settings": "Settings", "import": "Import" };
const dashboard$1 = { "title": "Dashboard", "spending_summary": "You spend {amount} out of every 10 euros", "periods": { "week": "Week", "month": "Month", "quarter": "Quarter", "year": "Year", "custom": "Custom" }, "dateRange": { "title": "Select Date Range", "startDate": "Start Date", "endDate": "End Date" }, "metrics": { "income": "Income", "expenses": "Expenses", "investments": "Investments", "balance": "Balance", "essential_expenses": "Essential expenses", "discretionary_expenses": "Discretionary expenses", "debt_payments": "Debt Payments", "saved_percentage": "{percentage}% saved" }, "charts": { "temporal_evolution": "Temporal evolution", "expense_distribution": "Expense and investment distribution", "temporal_evolution_subtitle": "Income and expense trends over time", "expense_distribution_subtitle": "Monthly comparison of essential, discretionary expenses and investments", "income_evolution": "Income Evolution", "expense_evolution": "Expense Evolution", "detailed_breakdown": "Detailed breakdown", "detailed_breakdown_subtitle": "Monthly expense analysis by category" }, "categories": { "title": "Expense breakdown", "food": "Food", "transport": "Transport", "utilities": "Utilities", "shopping": "Shopping", "entertainment": "Entertainment", "health": "Health" }, "status": { "excellent_control": "Excellent control", "moderate_control": "Moderate control", "high_spending": "High spending" } };
const transactions$1 = { "title": "Transactions", "add_transaction": "Add Transaction", "edit_transaction": "Edit Transaction", "description": "Description", "amount": "Amount", "category": "Category", "date": "Date", "merchant": "Merchant", "time": "Time", "observations_placeholder": "Add observation...", "observations_edit_tooltip": "Click to edit observations", "type": { "income": "Income", "expense": "Expense", "investment": "Investment" }, "modal": { "new_transaction": "New Transaction", "amount_placeholder": "0.00", "where_label": "Where?", "merchant_placeholder": "e.g., Amazon, Starbucks, Salary...", "what_for_label": "What for?", "description_placeholder": "Optional description...", "when_label": "When?", "expense": "Expense", "income": "Income", "save_transaction": "Save Transaction", "saving": "Saving...", "validation": { "amount_required": "Please enter a valid amount greater than 0", "merchant_required": "Merchant is required", "date_required": "Date is required", "future_date": "Date cannot be in the future" } }, "no_transactions": "No transactions", "delete_confirmation": "Are you sure you want to delete this transaction?", "delete_selected_title": "Delete Selected Transactions", "delete_selected_message": "Are you sure you want to delete {count} selected transactions? This action cannot be undone.", "delete_single_title": "Delete Transaction", "delete_single_message": "Are you sure you want to delete this transaction? This action cannot be undone.", "period": { "balance": "Period balance", "income": "Income", "total_expenses": "Total expenses", "expense_distribution": "Expense distribution", "essential": "Essential", "discretionary": "Discretionary", "uncategorized": "Uncategorized", "all_time": "All transactions" }, "search_placeholder": "Search transactions...", "select_all": "Select All", "select": "Select", "cancel": "Cancel", "add_category": "Add category", "show_transaction": "Show transaction", "hide_transaction": "Hide transaction", "delete_transaction": "Delete transaction", "today": "Today", "yesterday": "Yesterday", "delete_all": "Delete All" };
const categories$1 = { "title": "Categories", "add_category": "Add Category", "edit_category": "Edit Category", "name": "Name", "color": "Color", "icon": "Icon", "type": "Type", "no_categories": "No categories", "delete_confirmation": "Are you sure you want to delete this category?", "types": { "income": "Income", "investment": "Investment", "essential": "Essential Expense", "discretionary": "Discretionary Expense", "debt_payment": "Debt Payment", "no_compute": "No Compute" }, "helpers": { "no_compute": "'No Compute' categories are for account transfers (bank transfers, account movements, etc.) that shouldn't affect your financial metrics. They will appear in transactions but be excluded from expense and income analysis." } };
const settings$1 = { "title": "Settings", "language": "Language", "currency": "Currency", "theme": "Theme", "themes": { "light": "Light", "dark": "Dark", "system": "System" }, "data": "Data", "export_data": "Export Data", "import_data": "Import Data", "clear_data": "Clear Data", "clear_data_confirmation": "Are you sure you want to delete all data? This action cannot be undone.", "reset_data": "Reset to Defaults", "reset_data_confirmation": "This will restore all default categories and settings. Your transactions will be preserved but categories will be reset to defaults.", "export_success": "Data exported successfully", "import_success": "Successfully imported {count} transactions", "import_invalid_file": "Please select a valid JSON file", "import_file_too_large": "File size must be less than 10MB", "import_invalid_format": "Invalid backup file format", "import_confirmation": "This will import {transactions} transactions from {date}. Continue?", "import_parse_error": "Error parsing backup file", "import_read_error": "Error reading backup file" };
const errors$1 = { "generic": "An error occurred", "network": "Connection error", "validation": "Validation error", "not_found": "Not found", "unauthorized": "Unauthorized", "forbidden": "Forbidden" };
const success$1 = { "saved": "Saved successfully", "deleted": "Deleted successfully", "imported": "Imported successfully", "exported": "Exported successfully" };
const modal$1 = { "confirm_action": "Confirm Action", "are_you_sure": "Are you sure?", "delete_all_title": "Delete All Data", "delete_all_message": "⚠️ This will permanently delete ALL your transactions, categories, and settings from both the app and the database. This action cannot be undone!", "delete_everything": "Delete Everything", "reset_title": "Reset to Defaults", "reset_message": "⚠️ This will restore default categories and settings. Your transactions will be preserved, but custom categories and settings will be lost. This action cannot be undone!", "reset_everything": "Reset to Defaults" };
const accessibility$1 = { "close": "Close", "close_selector": "Close selector", "select_icon": "Select icon", "select_icon_for": "Select icon for {name}", "search_transactions": "Search transactions", "date_from": "From", "date_to": "To", "select_transactions": "Select transactions", "show_filters": "Show filters", "export_transactions": "Export transactions", "remove_income_filter": "Remove income filter", "remove_expense_filter": "Remove expense filter", "close_error_message": "Close error message", "show_period": "Show period", "show_all": "Show all", "select_language": "Select language", "more_actions": "More actions", "scroll_to_top": "Scroll to top", "filter_by_month": "Filter by month" };
const enTranslations = {
  common: common$1,
  navigation: navigation$1,
  dashboard: dashboard$1,
  "import": { "title": "Import Transactions", "subtitle": "Upload and process your bank CSV files with Japanese minimalist elegance", "steps": { "upload": "Upload", "upload_desc": "Choose file", "preview": "Preview", "preview_desc": "Review & Edit", "complete": "Complete", "complete_desc": "Import Done" }, "settings": { "title": "Import Settings", "enable_preview": "Enable preview before import", "enable_preview_desc": "Preview allows you to review and edit transactions before saving" }, "upload": { "choose_file": "Choose a CSV file", "drag_drop": "Or drag and drop your file here • Max 10MB", "processing": "Processing...", "ready": "Ready" }, "preview": { "stats": { "total": "Total", "selected": "Selected", "duplicates": "Duplicates", "skipped": "Skipped" }, "controls": { "show_duplicates": "Show duplicates", "show_all": "Show all transactions", "select_all": "Select All", "deselect_all": "Deselect All" }, "table": { "select": "Select", "date": "Date", "partner": "Partner", "description": "Description", "amount": "Amount", "status": "Status" }, "status": { "duplicate": "Duplicate", "ready": "Ready", "skipped": "Skipped" }, "pagination": { "showing": "Showing first 10 of {total} transactions", "show_all": "Show all" } }, "complete": { "importing": "Importing Transactions", "importing_desc": "Please wait while we save your data...", "success": "Import Complete!", "success_desc": "Successfully imported {count} transactions", "redirecting": "Redirecting to dashboard...", "import_another": "Import Another File" }, "actions": { "import_count": "Import {count} Transaction", "import_count_plural": "Import {count} Transactions" }, "errors": { "invalid_file": "Please select a CSV file", "file_too_large": "File size must be less than 10MB", "no_transactions": "No valid transactions found in file", "parse_failed": "Failed to parse CSV file", "import_failed": "Failed to import transactions" }, "duplicate_reasons": { "file": "Identical transaction found in file", "database": "Transaction already exists in database", "both": "Duplicate in both file and database" } },
  transactions: transactions$1,
  categories: categories$1,
  settings: settings$1,
  errors: errors$1,
  success: success$1,
  modal: modal$1,
  accessibility: accessibility$1
};
const common = { "confirm": "Confirmar", "cancel": "Cancelar", "delete": "Eliminar", "edit": "Editar", "save": "Guardar", "close": "Cerrar", "loading": "Cargando...", "search": "Buscar", "filter": "Filtrar", "reset": "Restablecer", "apply": "Aplicar", "yes": "Sí", "no": "No", "back": "Atrás", "done": "Hecho" };
const navigation = { "transactions": "Transacciones", "dashboard": "Panel", "categories": "Categorías", "settings": "Configuración", "import": "Importar" };
const dashboard = { "title": "Panel de Control", "spending_summary": "Gastas {amount} de cada 10 euros", "periods": { "week": "Semana", "month": "Mes", "quarter": "Trimestre", "year": "Año", "custom": "Personalizado" }, "dateRange": { "title": "Seleccionar Rango de Fechas", "startDate": "Fecha de Inicio", "endDate": "Fecha Final" }, "metrics": { "income": "Ingresos", "expenses": "Gastos", "investments": "Inversiones", "balance": "Balance", "essential_expenses": "Gastos esenciales", "discretionary_expenses": "Gastos discrecionales", "debt_payments": "Pago de Deudas", "saved_percentage": "{percentage}% ahorrado" }, "charts": { "temporal_evolution": "Evolución temporal", "expense_distribution": "Distribución de gastos e inversiones", "temporal_evolution_subtitle": "Tendencias de ingresos y gastos a lo largo del tiempo", "expense_distribution_subtitle": "Comparación mensual de gastos esenciales, discrecionales e inversiones", "income_evolution": "Evolución de Ingresos", "expense_evolution": "Evolución de Gastos", "detailed_breakdown": "Desglose detallado", "detailed_breakdown_subtitle": "Análisis mensual de gastos por categoría" }, "categories": { "title": "Desglose de gastos", "food": "Alimentación", "transport": "Transporte", "utilities": "Servicios", "shopping": "Compras", "entertainment": "Entretenimiento", "health": "Salud" }, "status": { "excellent_control": "Control excelente", "moderate_control": "Control moderado", "high_spending": "Gasto elevado" } };
const transactions = { "title": "Transacciones", "add_transaction": "Agregar Transacción", "edit_transaction": "Editar Transacción", "description": "Descripción", "amount": "Cantidad", "category": "Categoría", "date": "Fecha", "merchant": "Comercio", "time": "Hora", "observations_placeholder": "Añadir observación...", "observations_edit_tooltip": "Haz clic para editar observaciones", "type": { "income": "Ingreso", "expense": "Gasto", "investment": "Inversión" }, "modal": { "new_transaction": "Nueva Transacción", "amount_placeholder": "0.00", "where_label": "¿Dónde?", "merchant_placeholder": "ej., Amazon, Starbucks, Salario...", "what_for_label": "¿Para qué?", "description_placeholder": "Descripción opcional...", "when_label": "¿Cuándo?", "expense": "Gasto", "income": "Ingreso", "save_transaction": "Guardar Transacción", "saving": "Guardando...", "validation": { "amount_required": "Por favor ingresa una cantidad válida mayor a 0", "merchant_required": "El comercio es obligatorio", "date_required": "La fecha es obligatoria", "future_date": "La fecha no puede estar en el futuro" } }, "no_transactions": "No hay transacciones", "delete_confirmation": "¿Estás seguro de que quieres eliminar esta transacción?", "delete_selected_title": "Eliminar Transacciones Seleccionadas", "delete_selected_message": "¿Estás seguro de que quieres eliminar {count} transacciones seleccionadas? Esta acción no se puede deshacer.", "delete_single_title": "Eliminar Transacción", "delete_single_message": "¿Estás seguro de que quieres eliminar esta transacción? Esta acción no se puede deshacer.", "period": { "balance": "Balance del período", "income": "Ingresos", "total_expenses": "Gastos totales", "expense_distribution": "Distribución de gastos", "essential": "Esenciales", "discretionary": "Discrecionales", "uncategorized": "Sin categorizar", "all_time": "Todas las transacciones" }, "search_placeholder": "Buscar transacciones...", "select_all": "Seleccionar Todo", "select": "Seleccionar", "cancel": "Cancelar", "add_category": "Añadir categoría", "show_transaction": "Mostrar transacción", "hide_transaction": "Ocultar transacción", "delete_transaction": "Eliminar transacción", "today": "Hoy", "yesterday": "Ayer", "delete_all": "Eliminar Todo" };
const categories = { "title": "Categorías", "add_category": "Agregar Categoría", "edit_category": "Editar Categoría", "name": "Nombre", "color": "Color", "icon": "Icono", "type": "Tipo", "no_categories": "No hay categorías", "delete_confirmation": "¿Estás seguro de que quieres eliminar esta categoría?", "types": { "income": "Ingreso", "investment": "Inversión", "essential": "Gasto Esencial", "discretionary": "Gasto Discrecional", "debt_payment": "Pago de Deudas", "no_compute": "No Computar" }, "helpers": { "no_compute": "Las categorías 'No Computar' son para movimientos entre cuentas (transferencias, cambios de banco, etc.) que no deben afectar tus métricas financieras. Aparecerán en transacciones pero se excluirán de análisis de gastos e ingresos." } };
const settings = { "title": "Configuración", "language": "Idioma", "currency": "Moneda", "theme": "Tema", "themes": { "light": "Claro", "dark": "Oscuro", "system": "Sistema" }, "data": "Datos", "export_data": "Exportar Datos", "import_data": "Importar Datos", "clear_data": "Limpiar Datos", "clear_data_confirmation": "¿Estás seguro de que quieres eliminar todos los datos? Esta acción no se puede deshacer.", "reset_data": "Restablecer a Defaults", "reset_data_confirmation": "Esto restaurará todas las categorías y configuraciones por defecto. Tus transacciones se conservarán pero las categorías se restablecerán a las predeterminadas.", "export_success": "Datos exportados exitosamente", "import_success": "Se importaron exitosamente {count} transacciones", "import_invalid_file": "Por favor selecciona un archivo JSON válido", "import_file_too_large": "El archivo debe ser menor a 10MB", "import_invalid_format": "Formato de archivo de respaldo inválido", "import_confirmation": "Esto importará {transactions} transacciones desde {date}. ¿Continuar?", "import_parse_error": "Error al analizar archivo de respaldo", "import_read_error": "Error al leer archivo de respaldo" };
const errors = { "generic": "Ocurrió un error", "network": "Error de conexión", "validation": "Error de validación", "not_found": "No encontrado", "unauthorized": "No autorizado", "forbidden": "Prohibido" };
const success = { "saved": "Guardado exitosamente", "deleted": "Eliminado exitosamente", "imported": "Importado exitosamente", "exported": "Exportado exitosamente" };
const modal = { "confirm_action": "Confirmar Acción", "are_you_sure": "¿Estás seguro?", "delete_all_title": "Eliminar Todos los Datos", "delete_all_message": "⚠️ Esto eliminará permanentemente TODAS tus transacciones, categorías y configuraciones tanto de la aplicación como de la base de datos. ¡Esta acción no se puede deshacer!", "delete_everything": "Eliminar Todo", "reset_title": "Restablecer a Defaults", "reset_message": "⚠️ Esto restaurará las categorías y configuraciones por defecto. Tus transacciones se conservarán, pero las categorías personalizadas y configuraciones se perderán. ¡Esta acción no se puede deshacer!", "reset_everything": "Restablecer a Defaults" };
const accessibility = { "close": "Cerrar", "close_selector": "Cerrar selector", "select_icon": "Seleccionar icono", "select_icon_for": "Seleccionar icono para {name}", "search_transactions": "Buscar transacciones", "date_from": "Desde", "date_to": "Hasta", "select_transactions": "Seleccionar transacciones", "show_filters": "Mostrar filtros", "export_transactions": "Exportar transacciones", "remove_income_filter": "Eliminar filtro de ingresos", "remove_expense_filter": "Eliminar filtro de gastos", "close_error_message": "Cerrar mensaje de error", "show_period": "Mostrar período", "show_all": "Mostrar todas", "select_language": "Seleccionar idioma", "more_actions": "Más acciones", "scroll_to_top": "Ir arriba", "filter_by_month": "Filtrar por mes" };
const esTranslations = {
  common,
  navigation,
  dashboard,
  "import": { "title": "Importar Transacciones", "subtitle": "Carga y procesa tus archivos CSV bancarios con elegancia minimalista japonesa", "steps": { "upload": "Cargar", "upload_desc": "Elegir archivo", "preview": "Vista previa", "preview_desc": "Revisar y Editar", "complete": "Completar", "complete_desc": "Importación Hecha" }, "settings": { "title": "Configuración de Importación", "enable_preview": "Habilitar vista previa antes de importar", "enable_preview_desc": "La vista previa te permite revisar y editar transacciones antes de guardar" }, "upload": { "choose_file": "Elige un archivo CSV", "drag_drop": "O arrastra y suelta tu archivo aquí • Máx 10MB", "processing": "Procesando...", "ready": "Listo" }, "preview": { "stats": { "total": "Total", "selected": "Seleccionadas", "duplicates": "Duplicados", "skipped": "Omitidas" }, "controls": { "show_duplicates": "Mostrar duplicados", "show_all": "Mostrar todas las transacciones", "select_all": "Seleccionar Todo", "deselect_all": "Deseleccionar Todo" }, "table": { "select": "Seleccionar", "date": "Fecha", "partner": "Comercio", "description": "Descripción", "amount": "Cantidad", "status": "Estado" }, "status": { "duplicate": "Duplicado", "ready": "Listo", "skipped": "Omitido" }, "pagination": { "showing": "Mostrando las primeras 10 de {total} transacciones", "show_all": "Mostrar todas" } }, "complete": { "importing": "Importando Transacciones", "importing_desc": "Por favor espera mientras guardamos tus datos...", "success": "¡Importación Completada!", "success_desc": "Se importaron exitosamente {count} transacciones", "redirecting": "Redirigiendo al panel...", "import_another": "Importar Otro Archivo" }, "actions": { "import_count": "Importar {count} Transacción", "import_count_plural": "Importar {count} Transacciones" }, "errors": { "invalid_file": "Por favor selecciona un archivo CSV", "file_too_large": "El archivo debe ser menor a 10MB", "no_transactions": "No se encontraron transacciones válidas en el archivo", "parse_failed": "Error al procesar el archivo CSV", "import_failed": "Error al importar transacciones" }, "duplicate_reasons": { "file": "Transacción idéntica encontrada en el archivo", "database": "La transacción ya existe en la base de datos", "both": "Duplicado tanto en el archivo como en la base de datos" } },
  transactions,
  categories,
  settings,
  errors,
  success,
  modal,
  accessibility
};
const currentLanguage = writable("en");
const translations = {
  en: enTranslations,
  es: esTranslations
};
const t = derived(currentLanguage, ($currentLanguage) => {
  return (key, params) => {
    const keys = key.split(".");
    let value = translations[$currentLanguage];
    for (const k of keys) {
      value = value?.[k];
    }
    let result = value || key;
    if (params && typeof result === "string") {
      Object.entries(params).forEach(([paramKey, paramValue]) => {
        result = result.replace(
          new RegExp(`\\{${paramKey}\\}`, "g"),
          String(paramValue)
        );
      });
    }
    return result;
  };
});
function setLanguage(lang) {
  currentLanguage.set(lang);
}
export {
  currentLanguage as c,
  setLanguage as s,
  t
};
